"""Add esi_insurance_no field to visitor table

Revision ID: 2c9d474e1432
Revises: 02b5d29a0da9
Create Date: 2026-01-06 10:04:05.569481

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c9d474e1432'
down_revision = '02b5d29a0da9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('esi_insurance_no', sa.String(length=100), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('esi_insurance_no')

    # ### end Alembic commands ###
