"""Add from_datetime and to_datetime to Visitor model

Revision ID: 76b3661c82e0
Revises: 862c809ae402
Create Date: 2025-10-14 09:37:43.941323

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '76b3661c82e0'
down_revision = '862c809ae402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('from_datetime', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('to_datetime', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('to_datetime')
        batch_op.drop_column('from_datetime')

    # ### end Alembic commands ###
