"""Add approved_at to Visitor model and adjust check_in_time

Revision ID: 862c809ae402
Revises: 08fa7567703b
Create Date: 2025-10-09 16:04:55.189991

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '862c809ae402'
down_revision = '08fa7567703b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('approved_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('approved_at')

    # ### end Alembic commands ###
