"""add safety_measures_checklist to visitor table

Revision ID: 9f8a7d6c5e4b
Revises: 1b5e21dac2a3
Create Date: 2026-01-29 10:15:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f8a7d6c5e4b'
down_revision = '1b5e21dac2a3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('safety_measures_checklist', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('safety_measures_checklist')

    # ### end Alembic commands ###