"""add work_permit_certificate to visitor table

Revision ID: bbdcad1f27a6
Revises: 76b3661c82e0
Create Date: 2025-12-29 17:08:54.185890

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bbdcad1f27a6'
down_revision = '76b3661c82e0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('work_permit_certificate', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_column('work_permit_certificate')

    # ### end Alembic commands ###
