"""add ehs approval fields to visitor table

Revision ID: eb222b29865e
Revises: 9f8a7d6c5e4b
Create Date: 2026-01-29 12:33:16.994726

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb222b29865e'
down_revision = '9f8a7d6c5e4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ehs_approved', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ehs_approved_by_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ehs_approved_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('ehs_rejected', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('ehs_rejection_reason', sa.Text(), nullable=True))
        batch_op.create_foreign_key(None, 'user', ['ehs_approved_by_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('visitor', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('ehs_rejection_reason')
        batch_op.drop_column('ehs_rejected')
        batch_op.drop_column('ehs_approved_at')
        batch_op.drop_column('ehs_approved_by_id')
        batch_op.drop_column('ehs_approved')

    # ### end Alembic commands ###
